os: linux
dist: focal
language: ruby
services:
- docker
script:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build -t voltairemc/renderer:latest .
- docker push voltairemc/renderer:latest
env:
  global:
  - secure: nvp9zw2EVZphWGhwtzv5bJsplURHCGdDWfP8TNLdcz6goiZ2gamgAJJWzAgDibpXk/MuITDaV9VyyixdOwNGgL6UH8NM5vvi/vEQ5itWFMsXtJ5QLhhjnSQxQXinBFj6Ey34meLNHzVnefGDC4l1cl5rklq5ZEEbNS4Uj7hq8Lf+xrOf82xJ+oV9Ad/QtmsfXd+n87eQrii1bO0I9yylxy/BQ72AnPQIb21ocnzGJAUMGY+fUHCFz4GiV7qyY4OTq0dJda4knnSXBwOI+5GdNDw0D2ZgxW7t98puMeksQIzCP6rZZxo8bTmFGAV63vB/akrTSbK9TkZEdh1zEtZbMxZvkU049N9Hq2MD4L3A2qSw2xiTkkZoz+sy8zEOgd8mq2vdDKIk/ynXuafA9Nz3adD1rB4ZsahwYjCnXRcr7KNqOY7c8UMQJTl4Jf8mbHMiycLn4yKjjbSMFLjvqpiCewtLiwQHKQ3p+FaWtLDDb2VAvRvKE2mEJVWIRHN6bKw9uECcOmpiA5Js1uoDmoh+N0TFky16+qHZ9n53BPaFyJD02xR3TS8OjrvoqdYaeBx9daWigbYzOOF9U6v/XEc+aYFbOEXOO859IzrZX5FoYVYxag0AfZ+4EeMS86Jh98tfhCrp0Pi+/Xt5Z9pG8GiD9msGJjGNDjni8EGtG44gJjg=
  - secure: KQVrTn+6w9qOqAnBHaNVCnCgnF2nf69Wr4cF8QKI/Jdc2XUhS3USwKOJUETeP7sKUS7aZC+GoufPMtelthXtn8WE74nOEDrtgpG+C3/HPAAK1GZb0bYpl+3ZcUwS2WeJD7pUMt1HaefpEwCejZa9KEeXeLBk8vQ+MThyrEkg7N7YVEalzLQCsx4POjN/ASViM/QLJqpvD6waCQ3DZDUmrR3UmprR+nMedOAYis8muGJ7Vcl/1Uax9IxK5t+kOyVpTZZCKd3MlDEt1UO5wbwwCLSb4ofjGu/j2ga09TGQcrsvtnA5vQhsdyCm7chvQ/MJE7Ole5aX8ArOzuRbayQrR2lYZoTEMxrZrP/WfXZv71/nijBWLagQbtOkL3I7qEZXR/gCyFK4Ho71+hjAdWL4z9orPpFUfgcTd7fZAUZzNVbXCm+NStbo22zOH73IhGE93nzEjICROY4+BWKzEgj9D5/LFk2DEieg6QI+3+1LAX7Cjh2/x8ji/uCDFjH4oCEURE4tLP2SwJPscbmeCyYhH0A/eM3IxFDmwpnLKNz1L5ZDp9KQWMxXgHiCMCvcVxF+k8Rp9HBpNk8ai5TLbJctNofNJeYlFaqlKNXsbj2KBLE2SIxtknwsxwXqBHLuftUjCBHHCteSxGdXEPEqwi4CpiD0Qd6ptx8C5x0t7cEYvn0=
