on: [push, pull_request]
name: build and push
jobs:
    pipeline:
        runs-on: ubuntu-latest
        steps:
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: setup qemu
                uses: docker/setup-qemu-action@v1
            -
                name: setup docker
                uses: docker/setup-buildx-action@v1
            -
                name: login to github docker registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.CR_PAT }}
            -
                name: docker build and push
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: ghcr.io/${{ github.repository }}:latest
            -
                name: notify renderer
                uses: bsdlp/notify-docker-pull@6e3f9276c63e2e57a02c6841ac6aee71eb2646ff
                with:
                    server_url: "https://renderer.tonkat.su"
                    image: ghcr.io/${{ github.repository }}:latest